version: '3.5'

services:
    nginx:
        image: angular
        build:
            context: .
        container_name: angular
        volumes:
          - .:/app
        ports:
          - 4200:4200
        command: > 
          bash -c "ng serve --host 0.0.0.0 --port 4200"
